### ISSUE TITLE
Error starting simple-datatables with no data

### ISSUE THREAD

**Issue by sgi1e** [fiduswriter/simple-datatables#216]
`let dataTable = new DataTable("#myTable");`

```
simple-datatables.js:3 Uncaught TypeError: Cannot read properties of undefined (reading 'map')
    at T (simple-datatables.js:3:25733)
    at t.renderTable (simple-datatables.js:3:49945)
    at t.fixColumns (simple-datatables.js:3:58402)
    at t.render (simple-datatables.js:3:49870)
    at t.init (simple-datatables.js:3:47227)
    at new t (simple-datatables.js:3:46407)
    at initDataTable (Usuario:79:19)
    at inicio.js:6:18
    at HTMLDocument.<anonymous> (main.js:9:5)
```

**Comment by sgi1e** [comment]
Hello, the problem continues to persist. 
I am using the version @6.0.0-14

![2023-01-13-135722_1280x720_scrot](https://user-images.githubusercontent.com/88407620/212397825-fafd8d26-b0e6-4287-ab28-bbe76ee7154e.png)
