### ISSUE TITLE
Support JSON-loading with selective headers

### ISSUE THREAD

**Issue by tacman** [fiduswriter/simple-datatables#389]
- [X] I have looked through the [documentation](https://fiduswriter.github.io/simple-datatables/documentation/) to try to see if this feature already exists.
- [X] I have looked at the [demos](https://fiduswriter.github.io/simple-datatables/demos/) to see if one of them does what I want, but none of them did.

**Is your feature request related to a problem? Please describe.**
I want to load a table with just a few headers from my JSON, but it appears that you can't load from an array of JSON objects.

```javascript
const dataTable = new DataTable(this.element, {
    data: {
        headings: ['id', 'label'],
        data: [{'id': 1, 'label': 'Category 1'}]
    }
});
```

That gives the error

```
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'map')
    at simple-datatables.index-e8be4b2d41b4f4ca3cf9d1830ba2cb32.js:7:45718
    at Array.map (<anonymous>)
    at Q (simple-datatables.index-e8be4b2d41b4f4ca3cf9d1830ba2cb32.js:7:45617)
    at et.insert (simple-datatables.index-e8be4b2d41b4f4ca3cf9d1830ba2cb32.js:7:71514)
```

Is there another way to initialize this?

It doesn't make sense to use ConvertJSON, because it's not a JSON string, it's just an array of javascript objects.

Perhaps I'm missing something obvious, but I'm stuck.

Thanks.

**Comment by tacman** [comment]
This should work already, but even that simple script above is failing for me.  I'm on a bad network, could it somehow be related to that?

**Comment by tacman** [comment]
Bizarre -- working now. Before I was on a limited (and flaky) internet connection.  Not sure how that could be related.
